apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: medicore
spec:
  replicas: 2
  selector:
    matchLabels: { app: gateway }
  template:
    metadata:
      labels: { app: gateway }
    spec:
      containers:
        - name: gateway
          image: medicore/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: medicore
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
