apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-flow
  namespace: medicore
spec:
  replicas: 2
  selector:
    matchLabels: { app: patient-flow }
  template:
    metadata:
      labels: { app: patient-flow }
    spec:
      containers:
        - name: patient-flow
          image: medicore/patient-flow:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: ENV
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: patient-flow
  namespace: medicore
spec:
  selector:
    app: patient-flow
  ports:
    - port: 8082
      targetPort: 8082
